language: python
python:
  - 2.7

before_install:
  - git config --global user.email "surfer@frf.mil";
    git config --global user.name "surfer"
script:
  - VERBOSE=1 nosetests -v -s
branches:
  only:
    - master
notifications:
  email: false
